familyadmin/urls.py
from django.urls import path
from . import views

urlpatterns = [
    path("", views.FamilyListView.as_view(), name="family_list"),
    path("<int:pk>", views.FamilyDetailView.as_view(), name="family_detail"),
#    path("<str:upn>/print", views.FamilyPrintView.as_view(), name="family_print"),

]

website/urls.py
from django.conf import settings
from django.urls import include, path
from django.contrib import admin

from wagtail.admin import urls as wagtailadmin_urls
from wagtail import urls as wagtail_urls
from wagtail.documents import urls as wagtaildocs_urls
from wagtail.contrib.sitemaps.views import sitemap
from search import views as search_views

urlpatterns = [
    path('admin/', include('loginas.urls')),
    path("django-admin/", admin.site.urls),
    path("admin/", include(wagtailadmin_urls)),
    path("documents/", include(wagtaildocs_urls)),
    path("search/", search_views.search, name="search"),
    path("sitemap.xml", sitemap),
    path('', include('allauth.urls')),
    path('', include('userauth.urls')),

    path('registration/', include('registration.urls')),
    path('bookings/', include('bookings.urls')),

    path('eventadmin/', include('eventadmin.urls')),
    path('familyadmin/', include('familyadmin.urls')),
]


if settings.DEBUG:
    import debug_toolbar
    from django.conf.urls.static import static
    from django.contrib.staticfiles.urls import staticfiles_urlpatterns

    # Serve static and media files from development server
    urlpatterns += staticfiles_urlpatterns()
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

    urlpatterns += [path("__debug__/", include("debug_toolbar.urls"))]
    #urlpatterns += [path('django-admin/', admin.site.urls)]


urlpatterns += [

    # For anything not caught by a more specific rule above, hand over to
    # Wagtail's page serving mechanism. This should be the last pattern in
    # the list:
    path("", include(wagtail_urls)),
    # Alternatively, if you want Wagtail pages to be served from a subpath
    # of your site, rather than the site root:
    #    path("pages/", include(wagtail_urls)),
]

bookings/models.py
from django.db import models
from django.contrib.auth import get_user_model
from django.core.exceptions import ValidationError
from django.utils import timezone
from registration.models import FamilyMember
from events.models import EventPage

# from dateutil.relativedelta import relativedelta
# from datetime import *

User = get_user_model()


class Booking(models.Model):
    family = models.ForeignKey(User, on_delete=models.CASCADE)
    event = models.ForeignKey(EventPage, on_delete=models.CASCADE)
    booking_date = models.DateTimeField(help_text='Booking date/time', default=timezone.now)
#    status = models.BooleanField("Booked or Cancelled?", default=False)
#    cancelled_date = models.DateTimeField(help_text='Booking cancelled date/time', default=timezone.now)

    class Meta:
        ordering = ["-booking_date"]
        unique_together = ('family', 'event',)


    def __str__(self):
        return f"{self.family} - {self.event} - {self.booking_date}"


class Attendance(models.Model):
    booking = models.ForeignKey(Booking, on_delete=models.CASCADE)
    family_member = models.ForeignKey(FamilyMember, on_delete=models.CASCADE)
    attended = models.BooleanField("Attended event?", default=False)

    class Meta:
        unique_together = ('booking', 'family_member',)

    def __str__(self):
        return f"{self.family_member} - {self.attended}"

# TODO: Attendee must be a FamilyMember of the Family that Booked.

familyadmin/models.py
from django.db import models

# Create your models here.

familyadmin/views.py
import re

# from django.http import HttpResponseRedirect
# from django.shortcuts import get_object_or_404, render
# from django.urls import reverse
# from django.urls import reverse_lazy
from django.views import View
from django.views.generic.list import ListView
from django.views.generic.detail import DetailView
from django.views.generic.base import TemplateView
from django.contrib.auth.mixins import LoginRequiredMixin, UserPassesTestMixin

# For aggregation
# from django.db.models import Count
from django.db.models import Q

from django.contrib.auth import get_user_model
# from bookings.models import Booking, Attendance
# from events.models import EventPage
# from registration.models import FamilyMember

regex = re.compile('[^\da-zA-Z]')
User = get_user_model()


def is_member(user):
    # Used to restrict access to sensitive pages.
    return user.is_superuser or user.groups.filter(name='Editors').exists()


class FamilyBaseView(View):
    model = User
    fields = '__all__'


class FamilyListView(LoginRequiredMixin, UserPassesTestMixin, FamilyBaseView, ListView):
    template_name = 'familyadmin/family_list.html'
    context_object_name = 'family_list'

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        # Ensure q is a string in case a number is searched - e.g. student username starts with intake year.
        q = self.request.GET.get("q", "")

        if q:
            # First parameter is the replacement, second parameter is your input string
            qname = regex.sub('', q)

            context['qname'] = qname
        return context

    def get_queryset(self):
        q = self.request.GET.get("q")
        if q:
            return User.objects.filter(
                Q(family_name__icontains=q) | Q(email__icontains=q) | Q(first_name__icontains=q) | Q(last_name__icontains=q)
            )


    def test_func(self):
        return is_member(self.request.user)


class FamilyDetailView(LoginRequiredMixin, UserPassesTestMixin, FamilyBaseView, DetailView):
    template_name = 'familyadmin/family_detail.html'
    context_object_name = 'family'

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)

        # Should be able to drill down through user (family), but here it is for now...
        # family_members = FamilyMember.objects.filter(family=self)
        # context['family_members'] = family_members
        return context


    def test_func(self):
        return is_member(self.request.user)

website/templates/familyadmin/family_detail.html
{% extends "base.html" %}
{% load i18n static %}

{% block content %}
<div class="container">
    <div class="row justify-content-center">
        <div class="col-lg-8 col-md-10 col-sm-12">
            <div class="card">
                <div class="card-header">
                    <h3>{% trans "Family Details (Admin)" %}</h3>
                    <h4>{{ family.family_name }}</h4>
                </div>
                <div class="card-body">
                   <H5>User (Organiser)</H5>
                   <div class="container">
                   <div class="row">
                        <div class="col border">
                            <small>{% trans "First name" %}:</small><br>
                            {{ family.first_name|default:'' }}
                        </div>
                        <div class="col border">
                            <small>{% trans "Last name" %}:</small><br>
                            {{ family.last_name|default:'' }}
                        </div>
                    </div>
                    <div class="row">
                        <div class="col border">
                            <small>{% trans "E-mail" %}:</small><br>
                            {{ family.email }}
                        </div>
                    </div>
                    <div class="row">
                        <div class="col border">
                            <small>{% trans "Post Code" %}:</small><br>
                            {{ family.post_code }}
                        </div>
                        <div class="col border">
                            <small>{% trans "City" %}:</small><br>
                            {{ family.city }}
                        </div>
                    </div>
                    <div class="row">
                        <div class="col border">
                            <small>{% trans "Photo consent?" %}:</small><br>
                            {{ family.photo_consent|yesno:'Yes,No' }}
                        </div>
                        <div class="col border">
                            <small>{% trans "Contact mobile phone" %}:</small><br>
                            {{ family.contact_number }}
                        </div>
                    </div>
                    <div class="row">
                        <div class="col border">
                            <small>{% trans "Additional Information" %}:</small><br>
                            {{ family.additional_information }}
                        </div>
                    </div>
                </div>
                <br>
                <div class="container">
                   <H5>Family members</H5>
                    {% if family.family_member.all %}
                    <table class="table table-striped mt-2 sortable">
                        <thead>
                            <tr>
                                <th>#</th>
                                <th scope="col">Parent/Child</th>
                                <th scope="col">Name</th>
                                <th scope="col">DoB</th>
                                <th scope="col">Years Old</th>
                                <th scope="col">Gender</th>
                                <th scope="col">Dietary</th>
                                <th scope="col">Medical</th>
                                <th scope="col">FSM</th>
                                <th scope="col">SEN</th>
                                <th scope="col">School</th>
                            </tr>
                        </thead>
                        <tbody>
                                {% for family_member in family.family_member.all %}
                                <tr{% if family_member.type == "CHILD" %} class="table-primary"{% else %} class="table-warning"{% endif %}>
                                    <th scope="row">{{forloop.counter}}</th>
                                    <td> {{ family_member.get_type_display }}</td>
                                    <td> {{ family_member }}</td>
                                    <td> {{ family_member.childmore.dob|date:'j/m/Y' }}</td>
                                    <td class="text-center">{{ family_member.childmore.years_old }}</td>
                                    <td> {{ family_member.childmore.gender }}</td>
                                    <td> {{ family_member.dietary_req|yesno:"Yes," }}</td>
                                    <td> {{ family_member.medical_req|yesno:"Yes," }}</td>
                                    <td> {{ family_member.childmore.fsm|yesno:"Yes," }}</td>
                                    <td> {{ family_member.childmore.sen_req|yesno:"Yes," }}</td>
                                    <td> {{ family_member.childmore.school|default:'' }}</td>

                                </tr>
                                {% endfor %}
                        </tbody>
                    </table>
                    {% else %}
                    <B>No family members!</B>
                    {% endif %}
                </div>

                <div class="container">
                   <H5>Bookings</H5>
                   {% if family.booking_set.all %}
                    <table class="table table-striped mt-2 sortable">
                        <thead>
                            <tr>
                                <th>#</th>
                                <th class="text-center" scope="col">Event</th>
                                <th class="text-center" scope="col">Type</th>
                                <th class="text-center" scope="col">Booking Date</th>
                                <th class="text-center" scope="col"># Attendees</th>
                                <th class="text-left" scope="col">Attendees</th>
                                <th></th>
                            </tr>
                        </thead>
                        <tbody>
                            {% for booking in family.booking_set.all %}
                            <tr>
                                <th scope="row">{{forloop.counter}}</th>
                                <td class="text-left"><a href="{% url 'event_detail' booking.event.id %}">{{booking.event.title}}</a></td>
                                <td class="text-left">{{ booking.event.event_type }}</td>
                                <td class="text-center">{{booking.booking_date|date:'j/m/Y'}}</td>
                                <td class="text-center">{{ booking.attendance_set.all.count }}</td>
                                <td class="text-left">
                                    <ul class="list-group">
                                        {% for attendee in booking.attendance_set.all %}
                                        <li class="list-group-item {% if attendee.family_member.type == "CHILD" %} list-group-item-primary{% else %} list-group-item-warning{% endif %}">{{ attendee.family_member.first_name }} {{ attendee.family_member.last_name }}</li>
                                        {% endfor %}
                                    </ul>
                                </td>
                                <td><a class="btn btn-info" href="/django-admin/bookings/booking/{{ booking.id }}/change/" role="button">Edit</a></td>
                            </tr>
                            {% endfor %}
                        </tbody>
                    </table>
                    {% else %}
                    <B>No bookings!</B>
                    {% endif %}
                </div>

                <div class="card-footer text-muted text-center">
                    <a type="button" class="btn btn-info" href="{% url 'family_list' %}">Families</a>

                </div>
           </div>
        </div>
    </div>
</div>
    </div>

</div>

{% endblock  %}

website/templates/familyadmin/family_list.html
{% extends "base.html" %}

{% block title %}Family List{% endblock title %}

{% block content %}
<H1>Families</H1>

       <div class="d-flex justify-content-left">
         <form class="d-flex" action="{% url 'family_list' %}" method="get">
           <input class="form-control me-2" type="search" name="q" placeholder="Search" aria-label="Search" >
           <button class="btn btn-outline-success" type="submit">Search</button>
         </form>
       </div>
<BR>
{% if qname %}
<p>Searching for <b><em>{{ qname }}</em></b></p>
{% endif %}

      <table class="table table-striped mt-5 sortable">
            <thead>
                <tr>
                    <th>#</th>
                    <th class="text-left" scope="col">Family</th>
                    <th class="text-left" scope="col">E-Mail</th>
                    <th class="text-left" scope="col">First Name</th>
                    <th class="text-left" scope="col">Last Name</th>
                    <th class="text-left" scope="col">Photo Consent</th>
                    <th class="text-left" scope="col">Contact Number</th>
                    <th></th>
                </tr>
            </thead>
            <tbody>
           {% for family in family_list %}
               <tr>
                   <th scope="row">{{forloop.counter}}</th>
                   <td><a href="{% url 'family_detail' family.id %}">{{ family.family_name }}</a></td>
                   <td>{{ family.email }}</td>
                   <td>{{ family.first_name }}</td>
                   <td>{{ family.last_name }}</td>
                   <td>{{ family.photo_consent|yesno:'Yes,No' }}</td>
                   <td>{{ family.contact_number }}</td>
                   <td></td>
               </tr>
           {% endfor %}
            </tbody>
        </table>

{% endblock content %}